### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by whatever193** [MalinovyjMakintosh/Blum_software#1]
Have this error when create session 
Введите название сессии (для выхода нажмите Enter): 123
Traceback (most recent call last):
  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\Blum_software-main\Blum_software-main\main.py", line 100, in <module>
    asyncio.run(main())
  File "C:\Users\accli\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\accli\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\accli\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\Blum_software-main\Blum_software-main\main.py", line 97, in main
    await process()
  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\Blum_software-main\Blum_software-main\main.py", line 49, in process
    await create_sessions()
  File "C:\Users\accli\OneDrive\Desktop\Auto Game Tele\Blum_software-main\Blum_software-main\utils\core\register.py", line 18, in create_sessions
    async with session:
  File "C:\Users\accli\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\client.py", line 311, in __aenter__
    return await self.start()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\accli\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\accli\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "C:\Users\accli\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\client.py", line 616, in load_session
    await self.storage.open()
  File "C:\Users\accli\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\storage\file_storage.py", line 58, in open
    self.conn = sqlite3.connect(str(path), timeout=1, check_same_thread=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

**Comment by whatever193** [comment]
Fixed, Create sessions folder and it will work
